### ISSUE TITLE
Button group pattern(s)

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1091]
We could use a layout object for aligning a group of related buttons. This can be seen in our post-article notification area:

<img width="793" alt="Screen Shot 2020-12-15 at 10 15 08 AM" src="https://user-images.githubusercontent.com/69633/102255222-9fc30a80-3ebe-11eb-8695-ed47d764ede9.png">

And when replying to comments:

<img width="321" alt="Screen Shot 2020-12-15 at 10 15 59 AM" src="https://user-images.githubusercontent.com/69633/102255242-a782af00-3ebe-11eb-9de5-9608bc3428b6.png">

**Comment by gerardo-rodriguez** [comment]
I've been looking into this I have a question. 

Could we use the [List Inline object](https://v-next--cloudfour-patterns.netlify.app/?path=/docs/objects-list--default-story#inline-list) to handle this layout use case? What makes the Button Group pattern different or special that the List Inline object doesn't already provide? 🤔 

Thanks! 🙂

**Comment by gerardo-rodriguez** [comment]
Perhaps to answer my own question, I assume the ability to have a button group with tighter spacing might be a reason to have a Button Group pattern?

**Comment by gerardo-rodriguez** [comment]
Another difference is that the List object uses `flex-wrap: wrap`. I assume the Button Group should _not_ wrap.

**Comment by gerardo-rodriguez** [comment]
> Another difference is that the List object uses `flex-wrap: wrap`. I assume the Button Group should _not_ wrap.

Actually, this is not true when I look at the "Get Notifications" and "Get Weekly Digests" buttons. 

<img width="325" alt="Screen Shot 2021-05-27 at 9 00 49 AM" src="https://user-images.githubusercontent.com/459757/119859318-23e7d800-beca-11eb-8ebf-ffb7da18cc20.png">

Either way, it's feeling like there _should_ be a Button Group object to help with the layout. 

Now I'm thinking...

1. At smaller viewports, the buttons are stacked, I assume this component should handle this (in theory via `flex-wrap: wrap` and/or a media query)
2. The container only has `display: flex` at "small" (`min-width: 30em`) sizes and up
3. The "Get Notifications"/"Get Weekly Digests" buttons are `width: 100%`, it feels like the Button Group object shouldn't need to care about handling this?

Mmm...those are my thoughts for now. Back to continued development!

**Comment by Paul-Hebert** [comment]
These thoughts all make sense to me! I wonder about this part though:

>The "Get Notifications"/"Get Weekly Digests" buttons are width: 100%, it feels like the Button Group object shouldn't need to care about handling this?

If the buttons are going to be stacked vertically at small sizes it seems like they should be full width or it would feel awkward. Since this is a responsive behavior of the button group it would be nice for the button group to handle it. Maybe the button group CSS could do something like this?

```css
/* on small screens buttons stack vertically and are full width */
.o-button-group {
  align-items: stretch;
  display: flex;
  flex-direction: column;
}

/* they also have a vertical gap between them */
.o-button-group > * + * {
 margin-top: 1em; /* or something */
}

@media(min-width: 30em) {
  /* on large viewports, switch to a wrapping row */
  .o-button-group {
    flex-direction: row;
    flex-wrap: wrap;
  }
  
  /* and a horizontal gap */
  .o-button-group > * + * {
    margin-left: 1em; /* or something */
  }
}
```

What do you think?

(FWIW, I wish that `gap` was [better supported](https://caniuse.com/?search=gap) instead of doing the `* + *` margin business. The latest Safari _does_ support `gap`, but since Safari versions are tied to operating systems there are probably lots of devices on older versions.)
