### ISSUE TITLE
Background color pattern

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#1380]
We added a new prototype for the[ article listing page](https://v-next--cloudfour-patterns.netlify.app/?path=/story/prototypes-article-listing--example). There are multiple sections on the page. To differentiate between the sections, the background color alternates between white and light gray. We need a way to add background colors to containers. 

![v-next--cloudfour-patterns netlify app_iframe html_id=prototypes-article-listing--example args= viewMode=story(Chromebook 11)](https://user-images.githubusercontent.com/42841342/125142548-dd8eb700-e0cc-11eb-9b33-9fafbebbe823.png)

**Comment by gerardo-rodriguez** [comment]
@dromo77 @tylersticka I was looking to pick this up. The first solution that came to mind for me was adding a modifier class to the Container object. Am I way off? 🤔 😅

**Comment by tylersticka** [comment]
@gerardo-rodriguez I would shy away from solutions involving layout objects since the background impacts the appearance of the element moreso than its layout.

Chatting with @Paul-Hebert yesterday, I think he and I were leaning toward this being a simpler type of theme... something along the lines of...

```scss
.t-secondary {
  background-color: var(--theme-color-background-secondary);
}
```

But we also considered a new component:

```scss
.c-row:not(.c-row--alt):nth-child(even),
.c-row--alt:nth-child(odd) {
  background-color: var(--theme-color-background-secondary);
}
```

The way @Paul-Hebert summarized it at the time:

> Should any other component styles change within these sections? For example, if a nested component was going to have a grey background should it switch to a white background?
>
> (If so that feels like a theme. If not then a modifier class is probably sufficient. A theme is probably more flexible but trickier to set up since this theme would need to inherit properties from the theme its inside.)

While other color changes aren't necessary _now_, I can't promise we won't want them to be in the future, which was making me think this might be a theme.
