### ISSUE TITLE
Media with link

### ISSUE THREAD

**Issue by dromo77** [cloudfour/cloudfour.com-patterns#1435]
The [speaking prototype](https://v-next--cloudfour-patterns.netlify.app/?path=/story/prototypes-speaking-listing--example) uses the Media pattern to display upcoming talks. The Media object, including the text and Calendar Date, link to individual event pages. The Media object should be updated to support and format links. Either that or we may need a new pattern.

**Example**
![Screen Shot 2021-07-22 at 2 07 37 PM](https://user-images.githubusercontent.com/42841342/126709686-75bc18e6-6264-499b-95bf-7f49e99579a2.png)

**Comment by gerardo-rodriguez** [comment]
I was first leaning toward trying to make this work with the Media object as-is but I'm now not sure that's the best approach.

I was setting up the CSS something like this following what is done for [the Card component](https://github.com/cloudfour/cloudfour.com-patterns/blob/271ce1912ddf10317c258c6774683a558d3cf7a0/src/components/card/card.scss#L158):
```css
.o-media a::after {
  //   border-radius: size.$border-radius-medium;
  bottom: $_focus-overflow;
  content: '';
  left: $_focus-overflow;
  position: absolute;
  right: $_focus-overflow;
  top: $_focus-overflow;
  z-index: 1;
}
```

This _might_ work okay but it makes me a bit nervous that you can pass _anything_ into the Media object via the `content` block. What if there are multiple links? That seems like it would break my solution.

So now, I'm leaning toward making a new pattern that is a bit more pre-defined/controlled based on its intent. 

Does anyone else have any thoughts?
