### ISSUE TITLE
Simplify fluid calculations

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#1560]
We have [a number of fluid mixins and functions](https://github.com/cloudfour/cloudfour.com-patterns/blob/v-next/src/mixins/_fluid.scss) designed to gradually transition from a minimum to maximum size based on start and end breakpoints. This is based on some rather complicated math, covered in depth here:

- https://blog.typekit.com/2016/08/17/flexible-typography-with-css-locks/
- https://betterwebtype.com/articles/2019/05/14/the-state-of-fluid-web-typography/
- https://github.com/twbs/rfs

I suspect that these styles could be simplified using [a CSS `clamp()` function](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp()), which is [well supported now](https://caniuse.com/css-math-functions). But it's possible I'm misunderstanding the scope of that function, in which case this issue can be closed.

**Comment by Paul-Hebert** [comment]
I had the opportunity to dig into this a little on a recent client project. There are two ways clamp could be used for a similar effect:

## Naive Solution

We could avoid the complex calculations and do something like this:

```scss
@mixin font-size(
  $min,
  $max,
  $min-width: breakpoints.$small,
  $max-width: breakpoints.$large
) {
  font-size: $min;

  @media (min-width: $min-width) {
    font-size: clamp($min, calc(#{$min} + 1vw), $max);
  }

  @media (min-width: $max-width) {
    font-size: $max;
  }
}
```

This works but it can hit the max size before our breakpoint, or never hit the max size. This doesn't seem ideal>

## Cleaner solution

Or we could keep all the complex calculations, but ditch the media queries in favor of clamp. This has a couple of advantages:

- No media queries === slightly less CSS
- We no longer need to return multiple lines of code. Instead we can just return the `clamp()` string from a function. This means we don't have to write mixins for each type of rule we want to make fluid. Instead we can make one function and then use it wherever:

```scss
@function fluid-calc($min, $max, $min-width: breakpoints.$small, $max-width: breakpoints.$large) {
  $delta: unit.strip($max - $min);
  $delta-width: unit.strip($max-width - $min-width);
  $min-width-rem: unit.swap($min-width, rem); /* 1 */

  $calc: #{$min} + #{$delta} * ((100vw - #{$min-width-rem}) / #{$delta-width});

  @return clamp($min, $calc, $max);
}

.my-class {
  arbitrary-rule: fluid-calc(args);
}
```

This should be further tested and validated, but seems promising.
