### ISSUE TITLE
Simplify pagination items cap width

### ISSUE THREAD

**Issue by calebeby** [cloudfour/cloudfour.com-patterns#431]
I think it would be beneficial to replace this CSS:

https://github.com/cloudfour/cloudfour.com-patterns/blob/master/src/assets/toolkit/styles/components/pagination.css#L64
```css
.Pagination > *:nth-last-child(-n+5):first-child,
.Pagination > *:nth-last-child(-n+5):first-child ~ * {
  flex: 0 1 calc(100% / 8);
}
```

With a max-width on `.Pagination > *`

@tylersticka I'd like to hear more details about this:
> I'm not comfortable making that change in the pattern library because there's a lot of history and edge-cases to consider.
