### ISSUE TITLE
Use different plugin for css custom properties

### ISSUE THREAD

**Issue by calebeby** [cloudfour/cloudfour.com-patterns#434]
There are two competing plugins in the postcss community which try to provide css custom properties similar to the spec:

- https://github.com/MadLittleMods/postcss-css-variables
- https://github.com/postcss/postcss-custom-properties

The 2nd one is what is used in `postcss-preset-env`. I think we should investigate replacing it with `postcss-css-variables`.

`postcss-custom-properties`:
- Only lets you define custom properties in `:root`

`postcss-css-variables`:
- Allows you to define custom properties wherever, and it figures out scope based on a mostly-correct algorithm. In some cases it is impossible to know which variable will be in a scope with more specificity, but in most cases it is correct. [There are more details in the README](https://github.com/MadLittleMods/postcss-css-variables#caveats)

Also it is pretty smart at doing stuff like this:

```css
.foo {
  --bg: red;
  background: var(--bg);
}

@media screen and (max-width: 1000px) {
  .foo {
    --bg: green;
  }
}
```

to

```css
.foo {
  background: red;
}
@media screen and (max-width: 1000px) {
  .foo {
    background: green;
  }
}
```

I think switching to `postcss-css-variables` would be useful because then we don't have to have so many variables in the `:root` scope, and we wouldn't have to prefix the variables with the name of the pattern.

You can try it out here: https://madlittlemods.github.io/postcss-css-variables/playground/
