### ISSUE TITLE
Custom color property names should correspond with "webcolors"

### ISSUE THREAD

**Issue by erikjung** [cloudfour/cloudfour.com-patterns#46]
https://zaim.github.io/webcolors/

There was _some discussion_ about this a few months ago. Imposing this <s>constraint</s> <ins>guideline</ins> on color names will prevent our variables from gradually mutating into a mess of unmaintainable variations. We should end up with a list of colors that fall within this grouping:

``` css
/** 
 * Example from https://github.com/zaim/webcolors/blob/master/mrmrs/index.css 
 */

:root {
  --color-aqua: #7FDBFF;
  --color-blue: #0074D9;
  --color-lime: #01FF70;
  --color-navy: #001F3F;
  --color-teal: #39CCCC;
  --color-olive: #3D9970;
  --color-green: #2ECC40;
  --color-red: #FF4136;
  --color-maroon: #85144B;
  --color-orange: #FF851B;
  --color-purple: #B10DC9;
  --color-yellow: #FFDC00;
  --color-fuchsia: #F012BE;
  --color-gray: #AAAAAA;
  --color-white: #FFFFFF;
  --color-black: #111111;
  --color-silver: #DDDDDD;
}
```
