### ISSUE TITLE
Base styles

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#476]
It's pretty incredible [how small our CSS resets can be now](https://meowni.ca/posts/monica-dot-css/). But I do think there's value in establishing some very basic foundational styles. 

Off the top of my head…

```css
/**
 * Sensible box model
 */

*,
::before,
::after {
  box-sizing: border-box;
}

/**
 * Promote consistent line spacing.
 *
 * @see https://drafts.csswg.org/css-inline-3/#line-sizing-property
 */

html {
  line-sizing: normal;
}

/**
 * 1. Remove white space surrounding page.
 * 2. Prevent size adjustments on orientation change.
 * 3. Allow long words (like URLs) to break at arbitrary points.
 */

body {
  margin: 0; /* 1 */
  text-size-adjust: none; /* 2 */
  word-wrap: break-word; /* 3 */
}

/**
 * 1. Block display is usually what we want
 * 2. Remove strange space-below when inline
 * 3. Responsive by default
 * 
 * @see https://github.com/mozdevs/cssremedy
 */

audio,
canvas,
embed,
iframe,
img, 
object,
svg, 
video {
  display: block; /* 1 */
  vertical-align: middle; /* 2 */
  max-width: 100%; /* 3 */
}

canvas,
img,
svg, 
video {
  height: auto;
}

audio {
  width: 100%;
}

/**
 * Don't allow code blocks to overflow willy-nilly.
 */

pre {
  overflow: auto;
}

/**
 * Old browser fixes
 */

img {
  border-style: none;
}

[hidden] {
  display: none !important;
}

article,
aside,
figcaption,
figure,
footer,
header,
hgroup,
main,
nav,
section {
  display: block;
}
```
