### ISSUE TITLE
Support modular scale steps as Theo transforms

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#549]
This project uses a modular scale, but Theo has no built in way of defining modular scale steps. But it _does_ have a method of [defining custom value transforms](https://github.com/salesforce-ux/theo#custom-transforms--value-transforms).

In theory if we used Theo to read the value of the `ms.ratio` token first, we could then define `ms`, `ms/rem` and `ms/em` transforms that we apply based on a certain type or category value.

So something like this (just as a for instance):

```yaml
# design-tokens/sizes.yml
props:
  - name: pad_control_x
    value: 0
    type: ms-em
    category: sizing
  - name: pad_control_y
    value: -3
    type: ms-em
    category: sizing
```

Then referenced like this:

```scss
@use "../../design-tokens/sizes.yml";

.o-button {
  padding: sizes.$pad-y sizes.$pad-x;
}

.o-input {
  padding: sizes.$pad-y sizes.$pad-x;
}
```

Would compile to:

```css
.o-button {
  padding: .512em 1em;
}

.o-input {
  padding: .512em 1em;
}
```

Alternatively, there's no reason we couldn't just define those steps and then pipe the values into the `ms.step` mixin we already have. But having the transforms occur in our tokens might simplify our CSS and documentation a bit.
