### ISSUE TITLE
*-inline-start and *-inline-end utilities not functioning

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#661]
Not sure what happened, but some of the spacing utilities are no longer functioning as expected.

Examples circled in green are working correctly, in red are not:

<img width="1203" alt="Screen Shot 2020-04-27 at 1 13 25 PM" src="https://user-images.githubusercontent.com/69633/80417279-5a4bc180-888a-11ea-93dd-13c10c1854b7.png">

Possibly related to recent polyfill additions?

---

/CC @calebeby @Josh68

**Comment by Josh68** [comment]
FWIW, I was just looking at this, and it looks like the classes are not being output on those 2. Looks like @calebeby is checking this out, but let me know if you'd like me to have a look.

**Comment by calebeby** [comment]
In the `main.css` file generated by storybook:

```css
[dir="ltr"] .u-pad-inline-start-1{padding-left:1.25em !important}[dir="rtl"] .u-pad-inline-start-1{padding-right:1.25em !important}
```

The logical properties are being transpiled away. They shouldn't be, because all of the browsers we support support logical properties natively: https://caniuse.com/#feat=css-logical-props

When I saw that, I expected that adding `dir="ltr"` to the `html` tag would fix it, but it didn't 🤔

In the bundle generated in the gulp process, the output is different:

```css
.u-pad-inline-start-1 {
  padding-inline-start: 1.25em !important;
}
```

AFAICT this output is correct.

So this means that when postcss-preset-env is called by storybook, it is not respecting the browserslist, but when it is called via gulp, it is.

After I wrote that ☝️ I realized that we are not using postcss in the gulp output, it doesn't look like [this PR](https://github.com/cloudfour/cloudfour.com-patterns/pull/652) added that.

@Josh68 Can you look into adding postcss to the gulp build and figure out how to make postcss-preset-env not transpile logical properties (/ respect browserslist)?
