### ISSUE TITLE
Style critical Gutenberg block markup

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/cloudfour.com-patterns#710]
The new version of our WordPress theme will support [WordPress's Gutenberg editing experience](https://wordpress.org/gutenberg/).

We've already added markup examples for these blocks to Storybook (see #590). But some of these would benefit from some additional styles.

## How should we do this?

- [x] 1. Create a new `wordpress` directory in `src/third-party` or `src/vendor` (depending on the outcome of #709).

- [x] 1. Create one or more CSS files within that directory that style the WordPress Gutenberg blocks using the classes they provide.
    - If we have an equivalent pattern, we should use [Sass mixins](https://sass-lang.com/documentation/at-rules/mixin) to extend that pattern to the WordPress equivalent. For example, we could create a mixin that lets us apply the styles for `c-button` to `wp-block-button__link`.
    - If there is no equivalent pattern, we can author original styles.

## Why not modify the markup instead?

Since our patterns already include classes and markup structures for some Gutenberg patterns, it's reasonable to ask if we can customize their output. But I'd like to avoid that strategy for a few reasons:

- We tried [modifying markup of shortcodes](https://wordpress.org/support/topic/customizing-the-html-output-by-the-shortcode/) before, and those modifications ended up causing regressions when new features were added later on.
- Our incentive at the time for modifying markup was that existing markup did not use semantic HTML5 elements. This is no longer the case.
- Having this customization live mostly in CSS land gives more of the team an opportunity to contribute to their maintenance than if they were in PHP and React.
- Repeating CSS via mixins [has very low performance impact](https://csswizardry.com/2016/02/mixins-better-for-performance/) and is easier than ever [now that we're using Sass again](https://cloudfour.com/thinks/feeling-sassy-again/).

## Shouldn't this be in our WordPress theme?

A solid argument could be made that we should be exposing necessary mixins via the npm package and applying those as needed within the WordPress theme instead of doing that work here.

But our pattern work is much farther along than our theme work, and we already have markup examples, so it seems silly to needlessly complicate our short-term process.

## Priorities

There are currently 19 Gutenberg blocks we've documented [in our Storybook](https://v-next--cloudfour-patterns.netlify.app/?path=/docs/third-party-gutenberg--core-audio). Of those, I think we should prioritize the following:

- [x] import `@wordpress/block-library` styles (#778)
- [x] core/button (#729)
- [x] core/table (#743)
- [x] core/file (#773)
- [x] core/image (#754)
- [x] core/embed
- [x] ~core/columns~ (see https://github.com/cloudfour/cloudfour.com-patterns/issues/710#issuecomment-639093587)

The other blocks are either (a) mostly working already or (b) seem less likely to be used in the short term.

Where possible, I'd prefer these be submitted as separate PRs instead of one big PR.

**Comment by derekshirk** [comment]
👋 Hi @tylersticka, 

I wanted to ask you if you had any particular vision for column styles that you would like to see added to the existing WP Gutenberg output. 

Looking at the column output in Storybook we see the unstyled output. `wp-block-columns` has no associated styles, while its children `wp-block-column` elements receive inline `flex-basis` values. 

![Screen Shot 2020-06-04 at 11 43 25 AM](https://user-images.githubusercontent.com/1427548/83799882-5ebe8380-a65b-11ea-8da8-1590d61fa0b1.png)

While testing the columns block in a local Cloud Four site, I see that the default WP asset `block-library/style.css` includes some (somewhat suitable seeming) column styles. 

![Screen Shot 2020-06-04 at 11 04 23 AM](https://user-images.githubusercontent.com/1427548/83799876-5cf4c000-a65b-11ea-9849-99d66efeed3d.png)

![wp-columns](https://user-images.githubusercontent.com/1427548/83799887-60884700-a65b-11ea-9a1c-161ebb42f51f.gif)

From `/wp-includes/css/dist/block-library/style.css`: 

```css
.wp-block-columns {
  display: flex;
  margin-bottom: 28px;
  flex-wrap: wrap; 
}

@media (min-width: 782px) {
  .wp-block-columns {
      flex-wrap: nowrap; 
  } 
}

.wp-block-columns.has-background {
  padding: 20px 30px; 
}

.wp-block-column {
  flex-grow: 1;
  min-width: 0;
  word-break: break-word;
  overflow-wrap: break-word; 
}

@media (max-width: 599px) {
  .wp-block-column {
      flex-basis: 100% !important;
  }
}

@media (min-width: 600px) and (max-width: 781px) {
  .wp-block-column {
    flex-basis: calc(50% - 16px) !important;
    flex-grow: 0;
  }

  .wp-block-column:nth-child(even) {
    margin-left: 32px; 
  } 
}

@media (min-width: 782px) {
  .wp-block-column {
    flex-basis: 0;
    flex-grow: 1; 
  }
  .wp-block-column[style] {
    flex-grow: 0; 
  }
  .wp-block-column:not(:first-child) {
     margin-left: 32px; 
  } 
}
```

Were you hoping to see changes introduce other CSS column techniques? CSS Grid with `@supports`, improved responsive styling, or layout and spacing that makes better use of our spacing design tokens?
